### ISSUE TITLE
Conan Cache for Github action needs to detect when there are new packages to be wrote to the cache

### ISSUE THREAD

**Issue by Twon** [Twon/Morpheus#173]
Currently, if you update the Conan dependencies then new packages are not added to the cache. This is because once the cache exists it will not write the Conan package directory to the cache unless it finds new entries. However it currently has no way of detecting changes in the cache. 

The cache action support this by using the hashFiles command as outlined here: https://github.com/actions/cache/blob/main/caching-strategies.md#updating-cache-for-any-change-in-the-dependencies

```
  - uses: actions/cache@v3
    with:
      path: |
        path/to/dependencies
        some/other/dependencies
      key: cache-npm-${{ hashFiles('**/lockfiles') }}
      restore-keys: |
        cache-npm-
```

It's not yet clear to me how you get this information from Conan (i.e. which file would track new packages were downloads as they were not found in the cache).  Possibly could be related to the lockfiles mentioned for the install command here: https://docs.conan.io/1/reference/commands/consumer/install.html#lockfiles.  But requires further investigation.

**Comment by jakeheke75** [comment]
Hi Antony, let's see if with the lockfiles trick the Conan cache update is working. I tried to modify all the 3 workflow files and I am currently running some workflow tests. Will let you know!

**Comment by Twon** [comment]
Hey Gianmario,

Sounds good, let me know how you get on with the lockfile approach.  I'm not sure if that is the best approach.  Another alternative is outlined here is to hash the `conanfile.py` (as this contains the all package dependency info): https://github.com/turtlebrowser/conan-cache#example-using-the-builtin-github-cache-action-instead-for-conan

This will capture all updates but will also update anytime a change is made to the `conanfile.py` which results in saving the cache a bit more than necessary but will probably not have any significant downsides.

**Comment by jakeheke75** [comment]
Hi Antony, with the lockfile cache approach I did the following tests on my local branch:

![ci_run](https://github.com/Twon/Morpheus/assets/113254017/f656218b-bb18-45a0-9283-69f287b00e4d)

1. First run on the first build: I had as a dependency in the `conanfile.py` the package `boost 1.81.0`; the runtime was 57 minutes.
2. Second run without requirement change: this time the build run took probably advantage of the existing cache built in the previous step and the runtime was 17 minutes.
3. Third run with requirement change: I changed the dependency in the `conanfile.py` with package `boost 1.82.0`; the runtime was 39 minutes.
4. Fourth run without requirement change: in my expectation the runtime should be similar to what we got in step 2, but instead it was 27 minutes.

I have the impression that the build runtime is probably also affected by the actual workload of the machine...
Which is your opinion about those results?
Thanks,
Gianmario

**Comment by Twon** [comment]
Hey Gianmario,

So had a look through the build logs and what I can see is:

1. In the first build there is no cache (as caches are per user GitHub account, it does not share them between accounts, i.e. builds on your folk of Morpheus will not use the cache from my version of the project).  So the build takes 57 minutes as it builds all packages.  Once finished it pushes them to the cache.
2. The second build takes 17 minutes (note Linux took 5 minutes, but Windows is the slowest build here) but all packages are found in the cache.
3. The third build takes 39 minutes as here most packages are found in the cache, except for boost 1.82 which is not found in the cache so must be downloaded and built  Had the hashing worked then here boost 1.82 would have been put into the cache. You can see this in the 
```
Post job cleanup.
Cache hit occurred on the primary key build-ubuntu-latest-Release-gcc-1[2](https://github.com/jakeheke75/Morpheus/actions/runs/5513395757/jobs/10051480506#step:35:2)-libstdc++11
cache-, not saving cache. 
```
4. The fourth build is a repeat of the third, again it fetches and build boost 1.82 again.  

I can't account for the difference in time between the third and fourth builds as they look identical. It could be differences in the servers they run on, but I assume these are virtual machines / docker containers. 

However, I think the takeaway here is that the lockfile has not resulted in a partial update of the cache like we want.  I think at this point it make sense to try the hash of the conanfile.py.  So that would look like (note the hash will become the first component of the key:
```
    key: ${{ hashFiles('**/conanfile.py') }}-build-${{ matrix.os }}-${{ env.BUILD_TYPE }}-${{ env.COMPILER_TYPE }}-${{ env.COMPILER_VERSION }}-${{ env.STDLIB }}
    restore-keys: |
        ${{ hashFiles('**/conanfile.py') }}-build-${{ matrix.os }}-${{ env.BUILD_TYPE }}-${{ env.COMPILER_TYPE }}-${{ env.COMPILER_VERSION }}-
        ${{ hashFiles('**/conanfile.py') }}-build-${{ matrix.os }}-${{ env.BUILD_TYPE }}-${{ env.COMPILER_TYPE }}-
        ${{ hashFiles('**/conanfile.py') }}-build-${{ matrix.os }}-${{ env.BUILD_TYPE }}-
        ${{ hashFiles('**/conanfile.py') }}-build-${{ matrix.os }}-
```

Let me know if you have any questions or if any of that is not clear.

Cheers,
Antony

**Comment by jakeheke75** [comment]
Hi Antony,
Everything clear, thanks for the explanation. So I tried also to hash the `conanfile.py`.
And we could say that technically it worked.
![hashFile](https://github.com/Twon/Morpheus/assets/113254017/cad9e092-6492-47bb-befa-1bbf31db4146)

I deleted all the previous caches and at the first run the job "hashFiles conanfile.py" created the new cache as expected. All good.
```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/Morpheus/Morpheus --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~513 MB (538411273 B)
Cache saved successfully
Cache saved with key: 69932a981e2cc02d6b18c93e71a9cbcb05b7aafb8e3449f18cc344b18414a2c9-build-ubuntu-latest-Debug-gcc-12-libstdc++11:
```
Before the second run, I added just one comment in the `conanfile.py` without changing any dependency there. This was enough to change the hash of the file and therefore the old cache is not retrieved:

`Cache not found for input keys: 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-Debug-gcc-12-libstdc++11, 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-Debug-gcc-12-, 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-Debug-gcc-, 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-Debug-, 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-`

and a new cache has been created:
```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/Morpheus/Morpheus --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~514 MB (538528385 B)
Cache saved successfully
Cache saved with key: 95aff990afa0e2190bb288e0d838294eeb013b8c4fc3b10ddf0abaa95022d1f7-build-ubuntu-latest-Debug-gcc-12-libstdc++11
```
What do you think?
I am trying to investigate more the behaviour of the Conan lock files. I am trying to build the library with a lock file for the dependencies and see if we can have the update of the cache only in case that a dependency is changed.
If not successful then as you said we can probably live with the hash of the `conanfile.py`.
Thanks,
Gianmario

**Comment by jakeheke75** [comment]
Hi Antony,
I tested also the behaviour of the lockfiles to manage Conan dependencies. First of all I created the lockfiles folder in my local branch with the instruction `conan lock create conanfile.py --lockfile-out=locks/morpheus_pkg_deps.lock`.
The lock file content is basically the graph of the dependencies.
Then I executed the workflow jobs:
![lockfiles](https://github.com/Twon/Morpheus/assets/113254017/fec8e990-abf5-4685-9b0c-de5cb7a6e6cf)
the first job [test lockfile](https://github.com/jakeheke75/Morpheus/actions/runs/5548634227) was able create the new cache successfully:
```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/Morpheus/Morpheus --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~513 MB (538404309 B)
Cache saved successfully
Cache saved with key: b3bfa3a71666671a0be4161a17a0eb58c4d469319e841817a47ef6d58a163249-build-ubuntu-latest-Debug-gcc-12-libstdc++11
```
the second job [test lockfile with cache](https://github.com/jakeheke75/Morpheus/actions/runs/5549000971) was able to retrieve the cache successfully:
```
 Cache Size: ~513 MB (538404309 B)
/usr/bin/tar -xf /home/runner/work/_temp/c7efe6ec-2b10-457a-a890-13d644735a6a/cache.tzst -P -C /home/runner/work/Morpheus/Morpheus --use-compress-program unzstd
Cache restored successfully
Cache restored from key: b3bfa3a71666671a0be4161a17a0eb58c4d469319e841817a47ef6d58a163249-build-ubuntu-latest-Debug-gcc-12-libstdc++11
```
the third job [test lockfile change dependency](https://github.com/jakeheke75/Morpheus/actions/runs/5549149858) was able to find the cache and to recognize that the boost dependency has been updated:
```
conanfile.py (morpheus/0.0.1): Installing package
Requirements
    boost/1.82.0 from 'conancenter' - Downloaded
    bzip2/1.0.8 from 'conancenter' - Cache
    catch2/3.1.0 from 'conancenter' - Cache
    date/3.0.1 from 'conancenter' - Cache
    fmt/10.0.0 from 'conancenter' - Cache
    glbinding/3.1.0 from 'conancenter' - Cache
    glew/2.2.0 from 'conancenter' - Cache
    glu/system from 'conancenter' - Cache
    gtest/1.13.0 from 'conancenter' - Cache
    libbacktrace/cci.20210118 from 'conancenter' - Cache
    libcurl/8.0.1 from 'conancenter' - Cache
    magic_enum/0.8.2 from 'conancenter' - Cache
    ms-gsl/4.0.0 from 'conancenter' - Cache
    opengl/system from 'conancenter' - Cache
    openssl/3.1.1 from 'conancenter' - Cache
    range-v3/0.12.0 from 'conancenter' - Cache
    rapidjson/cci.20220822 from 'conancenter' - Cache
    tl-expected/20190710 from 'conancenter' - Cache
    trompeloeil/42 from 'conancenter' - Cache
    vulkan-headers/1.3.221 from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
```
but at the end of the build process the cache has not been updated with the new package:
```
Post job cleanup.
Cache hit occurred on the primary key b3bfa3a71666671a0be4161a17a0eb58c4d469319e841817a47ef6d58a163249-build-ubuntu-latest-Debug-gcc-12-libstdc++11, not saving cache.
```
So, if you agree, I will prepare a PR for the solution of hashing the `conanfile.py`. As you said even if we are saving the cache a bit more than necessary we can probably afford it.

Thanks,
Gianmario

**Comment by jakeheke75** [comment]
Cache unfortunately is immutable. As approximation we decided to hash the `conanfile.py`.
