### ISSUE TITLE
Support the Mold Linker

### ISSUE THREAD

**Issue by Twon** [Twon/Morpheus#179]
There is now a Conan package for Mold: https://conan.io/center/mold.  This should be added to the build.

**Comment by jakeheke75** [comment]
Hi Antony, I apologize for the newbie question. Is this just a matter of adding the Mold package and its dependencies to the `conanfile.py` or there is more? Thanks in advance!
Cheers,
Gianmario

**Comment by jakeheke75** [comment]
Hi Antony,
Just for information: the Mold linker can be used with the Conan recipe only if `build_type == "Release"` 
https://github.com/conan-io/conan-center-index/pull/11536#issuecomment-1195607330
This is the Conan recipe source code:
https://github.com/conan-io/conan-center-index/blob/1ede4d191660c9fcc0b7848744a8bcfb14cff626/recipes/mold/1.3.1/conanfile.py#L23-L25
I didn't expect that :disappointed:

**Comment by Twon** [comment]
Hey Gainmario, 

I think that is OK, it does not mean it will not work with debug builds, but it does mean that you have to specify release configuration in the conanfile settings so that in a debug build it uses the release build of Mold. As this is a build tool that is kind of what you want anyway (as it's not library code compiled into your library/application)

Does that make sense?

**Comment by jakeheke75** [comment]
Hello Antony,
Yes, it does make sense, sorry but I am a newbie also with Conan :smile:
it seemed strange to me to change the `self.settings.build_type` in `conanfile.py` just to accommodate the recipe rule of mold but now after your explanation I can see the reason.
I am drafting a PR, I will submit it as soon as I get a successful build.
Thanks,
Gianmario
