### ISSUE TITLE
Multi-Config Build issue

### ISSUE THREAD

**Issue by jakeheke75** [Twon/Morpheus#207]
Hi Antony,
I was trying to build with the Multi-Config instructions 
`conan install ./ -pr:h .conan2/profiles/msvc/193/x64-release -pr:b .conan2/profiles/msvc/193/x64-release --build missing -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"`
and I am getting the following errors:
```
-------- Installing package bzip2/1.0.8 (2 of 24) --------
bzip2/1.0.8: Building from source
bzip2/1.0.8: Package bzip2/1.0.8:cb7fa8bd12e6c820924b9d99de524771aa87e6fd
bzip2/1.0.8: Copying sources to build folder
bzip2/1.0.8: Building your package in ~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b
bzip2/1.0.8: Calling generate()
bzip2/1.0.8: Generators folder: ~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/build/generators
bzip2/1.0.8: CMakeToolchain generated: conan_toolchain.cmake
bzip2/1.0.8: CMakeToolchain generated: CMakePresets.json
bzip2/1.0.8: Generating aggregated env files
bzip2/1.0.8: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
bzip2/1.0.8: Calling build()
bzip2/1.0.8: apply_conandata_patches(): No patches defined in conandata
bzip2/1.0.8: Running CMake.configure()
bzip2/1.0.8: RUN: cmake -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/src/.."
-- Using Conan toolchain: ~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/build/CMakeFiles/CMakeOutput.log".

bzip2/1.0.8: ERROR: 
Package 'cb7fa8bd12e6c820924b9d99de524771aa87e6fd' build failed
bzip2/1.0.8: WARN: Build folder ~/dev/Morpheus/.conan2/p/b/bzip25f86810c7926f/b/build
*********************************************************
Recipe 'bzip2/1.0.8' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: bzip2/1.0.8: Error in build() method, line 63
	cmake.configure(build_script_folder=os.path.join(self.source_folder, os.pardir))
	ConanException: Error 1 while executing
```
	
I am investigating the reason for the error and how to fix it, any advice is welcome.
Thanks.
Cheers
Gianmario

**Comment by Twon** [comment]
Hey Gianmario,

Can you provide a bit more info so I can try and recreate.  Can you post the conan profile for this so that I can see which operating system and compiler configuration this is for.

Cheers

**Comment by jakeheke75** [comment]
Hi Antony,
I suspect this is another `PATH` issue. Note that in my Ubuntu Mate distro I don't have the Ninja executable installed.
I am starting from a clean build. I deleted the `.conan2` folder and launched the command `conan profile detect --force`:
```
detect_api: Found gcc 11
detect_api: gcc>=5, using the major as version
detect_api: gcc C++ standard library: libstdc++11

Detected profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
```
Then executing `conan config install ./.conan` and `conan install ./ -pr:h .conan2/profiles/gcc/12/x64-libstdc++11-release -pr:b .conan2/profiles/gcc/12/x64-libstdc++11-release --build missing -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"`.
Output:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=23
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
mold*:build_type=Release
mold*:compiler.libcxx=libstdc++11
onetbb*:build_type=Release
[conf]
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=23
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux
mold*:build_type=Release
mold*:compiler.libcxx=libstdc++11
onetbb*:build_type=Release
```
```
======== Computing dependency graph ========
...
ninja/1.11.1: Not found in local cache, looking in remotes...
ninja/1.11.1: Checking remote: conancenter
ninja/1.11.1: Downloaded recipe revision 77587f8c8318662ac8e5a7867eb4be21
...
ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Downloaded (conancenter)
...
ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21:3593751651824fb813502c69c971267624ced41a#60e6fc0f973babfbed66a66af22a4f02 - Download (conancenter)
```
Note that Ninja is not built, the executable is directly downloaded from conancenter and placed in directory `/Morpheus/.conan2/p/ninja6fed3c8400c5b/p/bin`. But the `PATH` has not been updated accordingly because if in the shell I try to invoke ninja I am getting the message `Command 'ninja' not found`.
And therefore the build command: 
`bzip2/1.0.8: RUN: cmake -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="/home/ipotti531/dev/Morpheus/.conan2/p/b/bzip2224ac0383bbe0/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/ipotti531/dev/Morpheus/.conan2/p/b/bzip2224ac0383bbe0/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "/home/ipotti531/dev/Morpheus/.conan2/p/b/bzip2224ac0383bbe0/b/src/.."`
is failing with the following error:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
```
So that's it. I am thinking, maybe as a test instead of downloading the binary package for Ninja we could force the build from source of the package. Maybe building from source will update the PATH accordingly?

**Comment by Twon** [comment]
Hey,

I think I see the problem here , I also ran into this issue. So although the conanfile includes Ninja as a build dependency this only applies to the Morpheus project, but not any of the dependencies it builds. The buildenv.sh file (and Windows equivalent bat file) which set Ninja on the path are only generated as a final step of the install process. Only after which when called/sourced will Ninja be available for use. So counter intuitive as it seem you will have to have Ninja installed on you system even when it's specified as a build dependency (or you do something similar to what we did with the mold setting so the build only puts the multi config Ninja setting onto Morpheus and not its dependencies).

Because of this issue we have to manually install Ninja on the github action workflows: https://github.com/Twon/Morpheus/blob/main/.github/workflows/cmake.yml#L77

Although it seems a bit strange than you can use build requirements to install build tools for a conan package, it does at least mean each conan package has control to specify how its built (accept for the aspect of why generator is used).

I hope this makes sense but let me know if anything is not clear.

Cheers

**Comment by jakeheke75** [comment]
Hi Antony,
Well as you said it's a bit counter intuitive but everything is clear now.
After installing ninja in the virtual environment the build was smooth.
I updated the documentation accordingly.
Thanks for the explanation. :pray: 
Cheers
Gianmario
